id = "rose-pine-icons"
name = "Rosé Pine Icons"
version = "0.1.0"
schema_version = 1
authors = ["ldakhoa1308 <ldakhoa1308@gmail.com>"]
description = "Port of the Rosé Pine VSCode icon theme to Zed."
repository = "https://github.com/ldakhoa/zed-rose-pine-icons"

icon_themes = ["icon_themes/rose-pine.json"]
